### ISSUE TITLE
Cannot run SkyDNS at IP 10.0.0.10

### ISSUE THREAD

**Issue by cwt** [skippbox/boot2k8s#13]
From kubelet.sh file set cluster DNS to 10.0.0.10
`--cluster-dns=10.0.0.10`

So, I would like to run SkyDNS as a service discovery, but the service cluster ip range set to **10.200.20.0/24**
`--service-cluster-ip-range=10.200.20.0/24`

The error message as below:
`The Service "kube-dns" is invalid.`
`spec.clusterIP: Invalid value: "10.0.0.10": provided IP is not in the valid range`

FYI: I'm running boot2k8s on VMware Fusion on OS X.

**Comment by sebgoa** [comment]
Hi @cwt could you try with kmachine https://github.com/skippbox/kmachine/releases

it sets up the DNS domain properly..

**Comment by cwt** [comment]
@runseb cool, I just test it and everything deployed.

Just one thing, from the [release note](https://github.com/skippbox/kmachine/releases)

> $ kmachine deploy dns barfoo
> $ kmachine deploy dashboard barfoo
> $ kmachine deploy helm barfoo

as in this format `$ kmachine deploy <service> <k8s-name>`

but, it actually need to swap service and k8s-name  like `$ kmachine deploy <k8s-name> <service>`

**Comment by sebgoa** [comment]
thanks, sorry about that, Just fixed that typo.
