### ISSUE TITLE
boot2k8s doesn't start standalone

### ISSUE THREAD

**Issue by sebgoa** [skippbox/boot2k8s#2]
due to this commit:
https://github.com/skippbox/boot2k8s/commit/991b5f67be96db73d10afefea9c48f422c7989e3

need a workaround if we don't use docker-machine to start it.

**Comment by cab105** [comment]
Have an idea where this could possibly be taken care of by a boot time argument that would be passed by docker-machine to disable starting the kubelet server.  Worst case, we let docker machine bring it down, install the updated files, and then attempt to bring it back up again.

**Comment by cab105** [comment]
Backed out with changeset: 669bf2a
