### ISSUE TITLE
kubectl port-forward broken because socat is missing from the iso

### ISSUE THREAD

**Issue by aszs** [skippbox/boot2k8s#9]
If you run `kubectl port-forward` and try to access the port it will fail with the error
"unable to do port forwarding: socat not found." and indeed it is not installed on the iso.

Unfortunately I was not able to use `tce_load` to install socat because the 64-bit version of socat is missing from the tinycore repos for some reason.  (You can access http://tinycorelinux.net/6.x/x86/tcz/socat.tcz but not http://tinycorelinux.net/6.x/x86_64/socat.tcz)

**Comment by sebgoa** [comment]
Hi, sorry for the delay.
This is now fixed by https://github.com/skippbox/boot2k8s/commit/bb3c207fee9f49ce83fe95aaabbec0ffb042648a

We are working on getting nsenter as well in the image.

A new release for k8s 1.2.0 is now available
